spring:
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/test_database0?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      password: root1234
      username: root
    test:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/test_database1?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      password: root1234
      username: root

  flyway:
    enabled: true
    locations: classpath:db/migration
    out-of-order: false
    baseline-on-migrate: true
  #    url: jdbc:mysql://localhost:3306/test_database0?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
#    user: root
#    password: root1234
---
spring:
  shardingsphere:
    sharding:
      default-data-source-name: test_database0
      tables:
        order:
          logic-table: order
          actual-data-nodes: test_database$->{0..1}.order_$->{0..9}
          database-strategy:
            inline:
              sharding-column: database_key
              algorithm-expression: test_database$->{database_key % 2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: order_$->{id % 10}
          key-generator:
            column: id
            type: MySnowFlake
            props:
              workid: 12
              datacenterid: 14

        audit_log:
          logic-table: audit_log
          actual-data-nodes: test_database0.audit_log_$->{0..9}
          table-strategy:
            standard:
              sharding-column: create_time
              precise-algorithm-class-name: com.noknow.shardingjdbcdemo.config.sharding.AuditLogAlgorithm
          key-generator:
            column: id
            type: UUID
    props:
      sql.show: true
      check.table.metadata.enabled: false


logging:
  level:
    org:
      springframework: debug
    com:
      noknow: debug

mybatis:
  mapper-locations: classpath:com/**/mapper/*.xml